override PROJECT_NAME := nesokia-chr-colors

# Version data
VER_MAJOR := 0
VER_MINOR := 1
VER_BUILD := 1

# Common root directory
DIR_ROOT := ../../..

# Common modules
COMMON_MODULES := png types

# Test dependencies
TEST_DEPS = $(DIR_BIN)/$(PROJECT_NAME)

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/lang/c.mk
