override PROJECT_NAME := nesokia-ines-inspect

# Version data
VER_MAJOR := 0
VER_MINOR := 4
VER_BUILD := 13

# Common root directory
DIR_ROOT := ../../..

# Linking flags
LDFLAGS := -lm

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/lang/c.mk


