override PROJECT_NAME := nesokia-ines-inspect

# Version data
VER_MAJOR := 0
VER_MINOR := 5
VER_BUILD := 15

# Common root directory
DIR_ROOT := ../../..

# Common modules
COMMON_MODULES := base error io log math strings types

# Test dependencies
TEST_DEPS = $(DIR_BIN)/$(PROJECT_NAME)

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/lang/c.mk
