override PROJECT_NAME := nesokia-chr-convert

# Version data
VER_MAJOR := 0
VER_MINOR := 4
VER_BUILD := 10

# Common root directory
DIR_ROOT := ../../..

# Linking flags
LDFLAGS := -lm -lpng

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/lang/c.mk


