override PROJECT_NAME := examples/platformer.nes

# Common root directory
DIR_ROOT := ../..

# CHR ROM banks
CHR_BANKS := CHR0 CHR1 CHR2 CHR3

CHR_BANK_CHR0_PNG := chrrom/png/bank-0.png
CHR_BANK_CHR0_CFG := chrrom/png/bank-0.cfg
CHR_BANK_CHR0_LEFT = $(CHR_OUTPUT_DIR)/bank-0.0000.chr
CHR_BANK_CHR0_RIGHT = $(CHR_OUTPUT_DIR)/bank-0.1000.chr
CHR_BANK_CHR0_PAL_BACK = $(PAL_OUTPUT_DIR)/back.pal
CHR_BANK_CHR0_PAL_SPRITES = $(PAL_OUTPUT_DIR)/sprites.pal

CHR_BANK_CHR1_PNG := chrrom/png/bank-1.png
CHR_BANK_CHR1_CFG := chrrom/png/bank-1.cfg
CHR_BANK_CHR1_LEFT = $(CHR_OUTPUT_DIR)/bank-1.0000.chr
CHR_BANK_CHR1_RIGHT = $(CHR_OUTPUT_DIR)/bank-1.1000.chr

CHR_BANK_CHR2_PNG := chrrom/png/bank-2.png
CHR_BANK_CHR2_CFG := chrrom/png/bank-2.cfg
CHR_BANK_CHR2_LEFT = $(CHR_OUTPUT_DIR)/bank-2.0000.chr
CHR_BANK_CHR2_RIGHT = $(CHR_OUTPUT_DIR)/bank-2.1000.chr

CHR_BANK_CHR3_PNG := chrrom/png/bank-3.png
CHR_BANK_CHR3_CFG := chrrom/png/bank-3.cfg
CHR_BANK_CHR3_LEFT = $(CHR_OUTPUT_DIR)/bank-3.0000.chr
CHR_BANK_CHR3_RIGHT = $(CHR_OUTPUT_DIR)/bank-3.1000.chr

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/asm.mk
