override PROJECT_NAME := nesokia-ines-header

# Version data
VER_MAJOR := 0
VER_MINOR := 2
VER_BUILD := 1

# Common root directory
DIR_ROOT := ../../..

include $(DIR_ROOT)/scripts/make/common.mk
include $(DIR_ROOT)/scripts/make/lang/dummy.mk


