; @file nsk_sprites_hud_counter.inc
; @brief Include module for the sprites counter part of the HUD drawing routines
;
; Part of the Nesokia project — MIT License.

.ifndef ::__NSK_SPRITES_HUD_COUNTER__
::__NSK_SPRITES_HUD_COUNTER__ = 1

.ifndef ::__NSK_SPRITES_HUD_COUNTER_ASM__

; @brief Draws the counter part of the HUD
.import nsk_sprites_hud_counter

; @brief Init module
.import nsk_sprites_hud_counter_init

.endif

.endif