; @file nsk_sprites_hud_fixed.inc
; @brief Include module for the sprites fixed part of the HUD drawing routines
;
; Part of the Nesokia project — MIT License.

.ifndef ::__NSK_SPRITES_HUD_FIXED__
::__NSK_SPRITES_HUD_FIXED__ = 1

.ifndef ::__NSK_SPRITES_HUD_FIXED_ASM__

; @brief Draws the fixed part of the HUD
.import nsk_sprites_hud_fixed

; @brief Init module
.import nsk_sprites_hud_fixed_init

.endif

.endif