; @file nsk_init_sprites_draw.inc
; @brief Include module for the sprites drawing init stage
;
; Part of the Nesokia project — MIT License.

.ifndef ::__NSK_INIT_SPRITES_DRAW__
::__NSK_INIT_SPRITES_DRAW__ = 1

.ifndef ::__NSK_INIT_SPRITES_DRAW_ASM__
; @brief Init stage for sprites drawing
; @warning Uses raw OAM access, requires rendering/NMI to be disabled
.import nsk_init_sprites_draw
.endif

.endif